<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.registry' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormRegistryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormRegistry.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormExtensionInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\Extension\\DependencyInjection\\DependencyInjectionExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\ResolvedFormTypeFactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\ResolvedFormTypeFactory.php';

return $this->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry(array(0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Form\\CorrelativoType' => function () {
    return ($this->privates['App\Form\CorrelativoType'] ?? ($this->privates['App\Form\CorrelativoType'] = new \App\Form\CorrelativoType()));
}, 'App\\Form\\DocumentoBajaType' => function () {
    return ($this->privates['App\Form\DocumentoBajaType'] ?? ($this->privates['App\Form\DocumentoBajaType'] = new \App\Form\DocumentoBajaType()));
}, 'App\\Form\\DocumentoExtraType' => function () {
    return ($this->privates['App\Form\DocumentoExtraType'] ?? ($this->privates['App\Form\DocumentoExtraType'] = new \App\Form\DocumentoExtraType()));
}, 'App\\Form\\DocumentoFormularioType' => function () {
    return ($this->privates['App\Form\DocumentoFormularioType'] ?? ($this->privates['App\Form\DocumentoFormularioType'] = new \App\Form\DocumentoFormularioType()));
}, 'App\\Form\\DocumentoProcesoType' => function () {
    return ($this->privates['App\Form\DocumentoProcesoType'] ?? ($this->privates['App\Form\DocumentoProcesoType'] = new \App\Form\DocumentoProcesoType()));
}, 'App\\Form\\DocumentoType' => function () {
    return ($this->privates['App\Form\DocumentoType'] ?? ($this->privates['App\Form\DocumentoType'] = new \App\Form\DocumentoType()));
}, 'App\\Form\\EnlacesType' => function () {
    return ($this->privates['App\Form\EnlacesType'] ?? ($this->privates['App\Form\EnlacesType'] = new \App\Form\EnlacesType()));
}, 'App\\Form\\FichaCargoType' => function () {
    return ($this->privates['App\Form\FichaCargoType'] ?? ($this->privates['App\Form\FichaCargoType'] = new \App\Form\FichaCargoType()));
}, 'App\\Form\\FilesType' => function () {
    return ($this->privates['App\Form\FilesType'] ?? ($this->privates['App\Form\FilesType'] = new \App\Form\FilesType()));
}, 'App\\Form\\MisionType' => function () {
    return ($this->privates['App\Form\MisionType'] ?? ($this->privates['App\Form\MisionType'] = new \App\Form\MisionType()));
}, 'App\\Form\\OrganigramaGerenciaType' => function () {
    return ($this->privates['App\Form\OrganigramaGerenciaType'] ?? ($this->privates['App\Form\OrganigramaGerenciaType'] = new \App\Form\OrganigramaGerenciaType()));
}, 'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => function () {
    return ($this->privates['form.type.entity'] ?? $this->load('getForm_Type_EntityService.php'));
}, 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => function () {
    return ($this->privates['form.type.choice'] ?? $this->load('getForm_Type_ChoiceService.php'));
}, 'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => function () {
    return ($this->privates['form.type.form'] ?? $this->load('getForm_Type_FormService.php'));
})), array('Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.form.transformation_failure_handling'] ?? $this->load('getForm_TypeExtension_Form_TransformationFailureHandlingService.php'));
    yield 1 => ($this->privates['form.type_extension.form.http_foundation'] ?? $this->load('getForm_TypeExtension_Form_HttpFoundationService.php'));
    yield 2 => ($this->privates['form.type_extension.form.validator'] ?? $this->load('getForm_TypeExtension_Form_ValidatorService.php'));
    yield 3 => ($this->privates['form.type_extension.upload.validator'] ?? $this->load('getForm_TypeExtension_Upload_ValidatorService.php'));
    yield 4 => ($this->privates['form.type_extension.csrf'] ?? $this->load('getForm_TypeExtension_CsrfService.php'));
}, 5), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.repeated.validator'] ?? ($this->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.submit.validator'] ?? ($this->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
}, 1)), new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_guesser.validator'] ?? $this->load('getForm_TypeGuesser_ValidatorService.php'));
    yield 1 => ($this->privates['form.type_guesser.doctrine'] ?? $this->load('getForm_TypeGuesser_DoctrineService.php'));
}, 2))), ($this->privates['form.resolved_type_factory'] ?? ($this->privates['form.resolved_type_factory'] = new \Symfony\Component\Form\ResolvedFormTypeFactory())));
