swiftmailer:
    transport: gmail
    username: procreator4all@gmail.com
    password: shades_on4the.vamps
    host: localhost
    port: 465
    encryption: ssl
    auth-mode: login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false