<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FichaCargo extends \App\Entity\FichaCargo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'id', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'fkarea', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'objetivo', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'responsabilidades', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'experiencia', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'conocimientos', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'formacion', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'caracteristicas', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'fechaaprobacion', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'fkjefeaprobador', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'firmajefe', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'fkgerenteaprobador', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'firmagerente', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'hipervinculo', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'estado'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'id', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'fkarea', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'objetivo', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'responsabilidades', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'experiencia', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'conocimientos', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'formacion', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'caracteristicas', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'fechaaprobacion', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'fkjefeaprobador', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'firmajefe', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'fkgerenteaprobador', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'firmagerente', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'hipervinculo', '' . "\0" . 'App\\Entity\\FichaCargo' . "\0" . 'estado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FichaCargo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(string $id): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkarea(): ?\App\Entity\GerenciaAreaSector
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkarea', []);

        return parent::getFkarea();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkarea(?\App\Entity\GerenciaAreaSector $fkarea): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkarea', [$fkarea]);

        return parent::setFkarea($fkarea);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjetivo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjetivo', []);

        return parent::getObjetivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjetivo(string $objetivo): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjetivo', [$objetivo]);

        return parent::setObjetivo($objetivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsabilidades(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsabilidades', []);

        return parent::getResponsabilidades();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsabilidades(string $responsabilidades): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsabilidades', [$responsabilidades]);

        return parent::setResponsabilidades($responsabilidades);
    }

    /**
     * {@inheritDoc}
     */
    public function getExperiencia(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperiencia', []);

        return parent::getExperiencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setExperiencia(string $experiencia): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExperiencia', [$experiencia]);

        return parent::setExperiencia($experiencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getConocimientos(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConocimientos', []);

        return parent::getConocimientos();
    }

    /**
     * {@inheritDoc}
     */
    public function setConocimientos(string $conocimientos): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConocimientos', [$conocimientos]);

        return parent::setConocimientos($conocimientos);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormacion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormacion', []);

        return parent::getFormacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormacion(string $formacion): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormacion', [$formacion]);

        return parent::setFormacion($formacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaracteristicas(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaracteristicas', []);

        return parent::getCaracteristicas();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaracteristicas(string $caracteristicas): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaracteristicas', [$caracteristicas]);

        return parent::setCaracteristicas($caracteristicas);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaaprobacion(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaaprobacion', []);

        return parent::getFechaaprobacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaaprobacion(\DateTimeInterface $fechaaprobacion): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaaprobacion', [$fechaaprobacion]);

        return parent::setFechaaprobacion($fechaaprobacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkjefeaprobador(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkjefeaprobador', []);

        return parent::getFkjefeaprobador();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkjefeaprobador(?\App\Entity\Usuario $fkjefeaprobador): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkjefeaprobador', [$fkjefeaprobador]);

        return parent::setFkjefeaprobador($fkjefeaprobador);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirmajefe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirmajefe', []);

        return parent::getFirmajefe();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirmajefe(string $firmajefe): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirmajefe', [$firmajefe]);

        return parent::setFirmajefe($firmajefe);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkgerenteaprobador(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkgerenteaprobador', []);

        return parent::getFkgerenteaprobador();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkgerenteaprobador(?\App\Entity\Usuario $fkgerenteaprobador): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkgerenteaprobador', [$fkgerenteaprobador]);

        return parent::setFkgerenteaprobador($fkgerenteaprobador);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirmagerente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirmagerente', []);

        return parent::getFirmagerente();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirmagerente(string $firmagerente): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirmagerente', [$firmagerente]);

        return parent::setFirmagerente($firmagerente);
    }

    /**
     * {@inheritDoc}
     */
    public function getHipervinculo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHipervinculo', []);

        return parent::getHipervinculo();
    }

    /**
     * {@inheritDoc}
     */
    public function setHipervinculo(string $hipervinculo): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHipervinculo', [$hipervinculo]);

        return parent::setHipervinculo($hipervinculo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(int $estado): \App\Entity\FichaCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

}
