<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DocumentoProceso extends \App\Entity\DocumentoProceso implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'id', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'nuevoactualizacion', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'fkdocumento', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'fkproceso', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'fktipo', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'versionvigente', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'vinculoarchivo', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'carpetaoperativa', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'aprobadorechazado', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'fkaprobador', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'fechaaprobacion', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'estado'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'id', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'nuevoactualizacion', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'fkdocumento', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'fkproceso', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'fktipo', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'versionvigente', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'vinculoarchivo', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'carpetaoperativa', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'aprobadorechazado', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'fkaprobador', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'fechaaprobacion', '' . "\0" . 'App\\Entity\\DocumentoProceso' . "\0" . 'estado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DocumentoProceso $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): \App\Entity\DocumentoProceso
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuevoactualizacion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuevoactualizacion', []);

        return parent::getNuevoactualizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuevoactualizacion(string $nuevoactualizacion): \App\Entity\DocumentoProceso
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuevoactualizacion', [$nuevoactualizacion]);

        return parent::setNuevoactualizacion($nuevoactualizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkdocumento(): ?\App\Entity\Documento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkdocumento', []);

        return parent::getFkdocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkdocumento(?\App\Entity\Documento $fkdocumento): \App\Entity\DocumentoProceso
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkdocumento', [$fkdocumento]);

        return parent::setFkdocumento($fkdocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkproceso(): ?\App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkproceso', []);

        return parent::getFkproceso();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkproceso(?\App\Entity\FichaProcesos $fkproceso): \App\Entity\DocumentoProceso
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkproceso', [$fkproceso]);

        return parent::setFkproceso($fkproceso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFktipo(): ?\App\Entity\TipoDocumento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFktipo', []);

        return parent::getFktipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFktipo(?\App\Entity\TipoDocumento $fktipo): \App\Entity\DocumentoProceso
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFktipo', [$fktipo]);

        return parent::setFktipo($fktipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo(string $titulo): \App\Entity\DocumentoProceso
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersionvigente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersionvigente', []);

        return parent::getVersionvigente();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersionvigente(string $versionvigente): \App\Entity\DocumentoProceso
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersionvigente', [$versionvigente]);

        return parent::setVersionvigente($versionvigente);
    }

    /**
     * {@inheritDoc}
     */
    public function getVinculoarchivo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVinculoarchivo', []);

        return parent::getVinculoarchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setVinculoarchivo(string $vinculoarchivo): \App\Entity\DocumentoProceso
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVinculoarchivo', [$vinculoarchivo]);

        return parent::setVinculoarchivo($vinculoarchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarpetaoperativa(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarpetaoperativa', []);

        return parent::getCarpetaoperativa();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarpetaoperativa(string $carpetaoperativa): \App\Entity\DocumentoProceso
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarpetaoperativa', [$carpetaoperativa]);

        return parent::setCarpetaoperativa($carpetaoperativa);
    }

    /**
     * {@inheritDoc}
     */
    public function getAprobadorechazado(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAprobadorechazado', []);

        return parent::getAprobadorechazado();
    }

    /**
     * {@inheritDoc}
     */
    public function setAprobadorechazado(string $aprobadorechazado): \App\Entity\DocumentoProceso
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAprobadorechazado', [$aprobadorechazado]);

        return parent::setAprobadorechazado($aprobadorechazado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkaprobador(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkaprobador', []);

        return parent::getFkaprobador();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkaprobador(?\App\Entity\Usuario $fkaprobador): \App\Entity\DocumentoProceso
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkaprobador', [$fkaprobador]);

        return parent::setFkaprobador($fkaprobador);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaaprobacion(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaaprobacion', []);

        return parent::getFechaaprobacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaaprobacion(\DateTimeInterface $fechaaprobacion): \App\Entity\DocumentoProceso
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaaprobacion', [$fechaaprobacion]);

        return parent::setFechaaprobacion($fechaaprobacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(int $estado): \App\Entity\DocumentoProceso
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

}
