<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FichaProcesos extends \App\Entity\FichaProcesos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'id', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'fkareagerenciasector', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'codproceso', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'objetivo', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'vigente', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'version', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'fechaemision', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'recursosnecesarios', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'entradasrequeridas', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'salidasesperadas', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'estado', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'fkusuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'id', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'fkareagerenciasector', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'codproceso', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'objetivo', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'vigente', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'version', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'fechaemision', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'recursosnecesarios', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'entradasrequeridas', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'salidasesperadas', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'estado', '' . "\0" . 'App\\Entity\\FichaProcesos' . "\0" . 'fkusuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FichaProcesos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(string $id): \App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkareagerenciasector(): ?\App\Entity\GerenciaAreaSector
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkareagerenciasector', []);

        return parent::getFkareagerenciasector();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkareagerenciasector(?\App\Entity\GerenciaAreaSector $fkareagerenciasector): \App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkareagerenciasector', [$fkareagerenciasector]);

        return parent::setFkareagerenciasector($fkareagerenciasector);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodproceso(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodproceso', []);

        return parent::getCodproceso();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodproceso(string $codproceso): \App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodproceso', [$codproceso]);

        return parent::setCodproceso($codproceso);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjetivo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjetivo', []);

        return parent::getObjetivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjetivo(string $objetivo): \App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjetivo', [$objetivo]);

        return parent::setObjetivo($objetivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getVigente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVigente', []);

        return parent::getVigente();
    }

    /**
     * {@inheritDoc}
     */
    public function setVigente(string $vigente): \App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVigente', [$vigente]);

        return parent::setVigente($vigente);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', []);

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion(string $version): \App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', [$version]);

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaemision(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaemision', []);

        return parent::getFechaemision();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaemision(\DateTimeInterface $fechaemision): \App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaemision', [$fechaemision]);

        return parent::setFechaemision($fechaemision);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntradasrequeridas(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntradasrequeridas', []);

        return parent::getEntradasrequeridas();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntradasrequeridas(string $entradasrequeridas): \App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntradasrequeridas', [$entradasrequeridas]);

        return parent::setEntradasrequeridas($entradasrequeridas);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalidasesperadas(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalidasesperadas', []);

        return parent::getSalidasesperadas();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalidasesperadas(string $salidasesperadas): \App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalidasesperadas', [$salidasesperadas]);

        return parent::setSalidasesperadas($salidasesperadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecursosnecesarios(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecursosnecesarios', []);

        return parent::getRecursosnecesarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecursosnecesarios(string $recursosnecesarios): \App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecursosnecesarios', [$recursosnecesarios]);

        return parent::setRecursosnecesarios($recursosnecesarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(int $estado): \App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

}
