<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Accion extends \App\Entity\Accion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'fkhallazgo', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'ordinal', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'fechaimplementacion', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'responsableimplementacion', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'estadoaccion', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'responsableregistro', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'fecharegistro', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'estado'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'fkhallazgo', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'ordinal', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'fechaimplementacion', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'responsableimplementacion', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'estadoaccion', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'responsableregistro', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'fecharegistro', '' . "\0" . 'App\\Entity\\Accion' . "\0" . 'estado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Accion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(string $id): \App\Entity\Accion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkhallazgo(): ?\App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkhallazgo', []);

        return parent::getFkhallazgo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkhallazgo(?\App\Entity\Hallazgo $fkhallazgo): \App\Entity\Accion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkhallazgo', [$fkhallazgo]);

        return parent::setFkhallazgo($fkhallazgo);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdinal(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdinal', []);

        return parent::getOrdinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrdinal(int $ordinal): \App\Entity\Accion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrdinal', [$ordinal]);

        return parent::setOrdinal($ordinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion(string $descripcion): \App\Entity\Accion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaimplementacion(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaimplementacion', []);

        return parent::getFechaimplementacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaimplementacion(\DateTimeInterface $fechaimplementacion): \App\Entity\Accion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaimplementacion', [$fechaimplementacion]);

        return parent::setFechaimplementacion($fechaimplementacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsableimplementacion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsableimplementacion', []);

        return parent::getResponsableimplementacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsableimplementacion(string $responsableimplementacion): \App\Entity\Accion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsableimplementacion', [$responsableimplementacion]);

        return parent::setResponsableimplementacion($responsableimplementacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoaccion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoaccion', []);

        return parent::getEstadoaccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoaccion(string $estadoaccion): \App\Entity\Accion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoaccion', [$estadoaccion]);

        return parent::setEstadoaccion($estadoaccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsableregistro(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsableregistro', []);

        return parent::getResponsableregistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsableregistro(string $responsableregistro): \App\Entity\Accion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsableregistro', [$responsableregistro]);

        return parent::setResponsableregistro($responsableregistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecharegistro(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecharegistro', []);

        return parent::getFecharegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecharegistro(\DateTimeInterface $fecharegistro): \App\Entity\Accion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecharegistro', [$fecharegistro]);

        return parent::setFecharegistro($fecharegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(int $estado): \App\Entity\Accion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

}
