<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personal extends \App\Entity\Personal implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'apellido', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'ci', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'correo', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'fnac', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'estado', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'fkprocesoscargo', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'fkestadopersonal'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'apellido', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'ci', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'correo', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'fnac', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'estado', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'fkprocesoscargo', '' . "\0" . 'App\\Entity\\Personal' . "\0" . 'fkestadopersonal'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Personal $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): \App\Entity\Personal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getFnac(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFnac', []);

        return parent::getFnac();
    }

    /**
     * {@inheritDoc}
     */
    public function setFnac(\DateTimeInterface $fnac): \App\Entity\Personal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFnac', [$fnac]);

        return parent::setFnac($fnac);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', []);

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido(string $apellido): \App\Entity\Personal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', [$apellido]);

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\Personal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono(int $telefono): \App\Entity\Personal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getCi(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCi', []);

        return parent::getCi();
    }

    /**
     * {@inheritDoc}
     */
    public function setCi(int $ci): \App\Entity\Personal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCi', [$ci]);

        return parent::setCi($ci);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', []);

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo(string $correo): \App\Entity\Personal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', [$correo]);

        return parent::setCorreo($correo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(int $estado): \App\Entity\Personal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkPersonalCargo(): ?\App\Entity\PersonalCargo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkPersonalCargo', []);

        return parent::getFkPersonalCargo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkPersonalCargo(?\App\Entity\PersonalCargo $fkprocesoscargo): \App\Entity\Personal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkPersonalCargo', [$fkprocesoscargo]);

        return parent::setFkPersonalCargo($fkprocesoscargo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkestadopersonal(): ?\App\Entity\EstadoPersonal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkestadopersonal', []);

        return parent::getFkestadopersonal();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkestadopersonal(?\App\Entity\EstadoPersonal $fkestadopersonal): \App\Entity\Personal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkestadopersonal', [$fkestadopersonal]);

        return parent::setFkestadopersonal($fkestadopersonal);
    }

}
