<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Auditoria extends \App\Entity\Auditoria implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'codigo', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'fkarea', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'fktipo', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'fechaprogramada', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'duracionestimada', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'lugar', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'alcance', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'objetivos', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'fechahorainicio', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'fechahorafin', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'conclusiones', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'responsable', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'fecharegistro', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'estado'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'codigo', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'fkarea', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'fktipo', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'fechaprogramada', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'duracionestimada', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'lugar', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'alcance', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'objetivos', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'fechahorainicio', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'fechahorafin', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'conclusiones', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'responsable', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'fecharegistro', '' . "\0" . 'App\\Entity\\Auditoria' . "\0" . 'estado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Auditoria $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo(string $codigo): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkarea(): ?\App\Entity\GerenciaAreaSector
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkarea', []);

        return parent::getFkarea();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkarea(?\App\Entity\GerenciaAreaSector $fkarea): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkarea', [$fkarea]);

        return parent::setFkarea($fkarea);
    }

    /**
     * {@inheritDoc}
     */
    public function getFktipo(): ?\App\Entity\TipoAuditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFktipo', []);

        return parent::getFktipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFktipo(?\App\Entity\TipoAuditoria $fktipo): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFktipo', [$fktipo]);

        return parent::setFktipo($fktipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaprogramada(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaprogramada', []);

        return parent::getFechaprogramada();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaprogramada(\DateTimeInterface $fechaprogramada): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaprogramada', [$fechaprogramada]);

        return parent::setFechaprogramada($fechaprogramada);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuracionestimada(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuracionestimada', []);

        return parent::getDuracionestimada();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuracionestimada(int $duracionestimada): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuracionestimada', [$duracionestimada]);

        return parent::setDuracionestimada($duracionestimada);
    }

    /**
     * {@inheritDoc}
     */
    public function getLugar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugar', []);

        return parent::getLugar();
    }

    /**
     * {@inheritDoc}
     */
    public function setLugar(string $lugar): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugar', [$lugar]);

        return parent::setLugar($lugar);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlcance(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlcance', []);

        return parent::getAlcance();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlcance(string $alcance): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlcance', [$alcance]);

        return parent::setAlcance($alcance);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjetivos(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjetivos', []);

        return parent::getObjetivos();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjetivos(string $objetivos): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjetivos', [$objetivos]);

        return parent::setObjetivos($objetivos);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechahorainicio(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechahorainicio', []);

        return parent::getFechahorainicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechahorainicio(\DateTimeInterface $fechahorainicio): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechahorainicio', [$fechahorainicio]);

        return parent::setFechahorainicio($fechahorainicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechahorafin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechahorafin', []);

        return parent::getFechahorafin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechahorafin(\DateTimeInterface $fechahorafin): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechahorafin', [$fechahorafin]);

        return parent::setFechahorafin($fechahorafin);
    }

    /**
     * {@inheritDoc}
     */
    public function getConclusiones(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConclusiones', []);

        return parent::getConclusiones();
    }

    /**
     * {@inheritDoc}
     */
    public function setConclusiones(string $conclusiones): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConclusiones', [$conclusiones]);

        return parent::setConclusiones($conclusiones);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsable(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsable', []);

        return parent::getResponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsable(string $responsable): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsable', [$responsable]);

        return parent::setResponsable($responsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecharegistro(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecharegistro', []);

        return parent::getFecharegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecharegistro(\DateTimeInterface $fecharegistro): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecharegistro', [$fecharegistro]);

        return parent::setFecharegistro($fecharegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(int $estado): \App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

}
