<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Modulo extends \App\Entity\Modulo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Modulo' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Modulo' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Modulo' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Modulo' . "\0" . 'ruta', '' . "\0" . 'App\\Entity\\Modulo' . "\0" . 'icono', '' . "\0" . 'App\\Entity\\Modulo' . "\0" . 'menu', '' . "\0" . 'App\\Entity\\Modulo' . "\0" . 'fkmodulo'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Modulo' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Modulo' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Modulo' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Modulo' . "\0" . 'ruta', '' . "\0" . 'App\\Entity\\Modulo' . "\0" . 'icono', '' . "\0" . 'App\\Entity\\Modulo' . "\0" . 'menu', '' . "\0" . 'App\\Entity\\Modulo' . "\0" . 'fkmodulo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Modulo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(string $id): \App\Entity\Modulo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\Modulo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo(string $titulo): \App\Entity\Modulo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getRuta(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRuta', []);

        return parent::getRuta();
    }

    /**
     * {@inheritDoc}
     */
    public function setRuta(string $ruta): \App\Entity\Modulo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRuta', [$ruta]);

        return parent::setRuta($ruta);
    }

    /**
     * {@inheritDoc}
     */
    public function getIcono(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIcono', []);

        return parent::getIcono();
    }

    /**
     * {@inheritDoc}
     */
    public function setIcono(string $icono): \App\Entity\Modulo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIcono', [$icono]);

        return parent::setIcono($icono);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenu(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenu', []);

        return parent::getMenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenu(int $menu): \App\Entity\Modulo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenu', [$menu]);

        return parent::setMenu($menu);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkmodulo(): ?\App\Entity\Modulo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkmodulo', []);

        return parent::getFkmodulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkmodulo(?\App\Entity\Modulo $fkmodulo): \App\Entity\Modulo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkmodulo', [$fkmodulo]);

        return parent::setFkmodulo($fkmodulo);
    }

}
