<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class GerenciaAreaSector extends \App\Entity\GerenciaAreaSector implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'id', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'fkresponsable', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'codigo', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'vigente', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'fkgerencia', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'fkarea', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'fksector', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'estado'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'id', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'fkresponsable', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'codigo', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'vigente', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'fkgerencia', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'fkarea', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'fksector', '' . "\0" . 'App\\Entity\\GerenciaAreaSector' . "\0" . 'estado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (GerenciaAreaSector $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): \App\Entity\GerenciaAreaSector
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(int $estado): \App\Entity\GerenciaAreaSector
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkresponsable(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkresponsable', []);

        return parent::getFkresponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkresponsable(\App\Entity\Usuario $fkresponsable): \App\Entity\GerenciaAreaSector
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkresponsable', [$fkresponsable]);

        return parent::setFkresponsable($fkresponsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo(string $codigo): \App\Entity\GerenciaAreaSector
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getVigente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVigente', []);

        return parent::getVigente();
    }

    /**
     * {@inheritDoc}
     */
    public function setVigente(string $vigente): \App\Entity\GerenciaAreaSector
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVigente', [$vigente]);

        return parent::setVigente($vigente);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkgerencia(): ?\App\Entity\Gerencia
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkgerencia', []);

        return parent::getFkgerencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkgerencia(?\App\Entity\Gerencia $fkgerencia): \App\Entity\GerenciaAreaSector
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkgerencia', [$fkgerencia]);

        return parent::setFkgerencia($fkgerencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkarea(): ?\App\Entity\Area
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkarea', []);

        return parent::getFkarea();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkarea(?\App\Entity\Area $fkarea): \App\Entity\GerenciaAreaSector
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkarea', [$fkarea]);

        return parent::setFkarea($fkarea);
    }

    /**
     * {@inheritDoc}
     */
    public function getFksector(): ?\App\Entity\Sector
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFksector', []);

        return parent::getFksector();
    }

    /**
     * {@inheritDoc}
     */
    public function setFksector(?\App\Entity\Sector $fksector): \App\Entity\GerenciaAreaSector
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFksector', [$fksector]);

        return parent::setFksector($fksector);
    }

}
