<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RiesgosOportunidades extends \App\Entity\RiesgosOportunidades implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'id', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'fktipo', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'fkficha', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'origen', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'fkprobabilidad', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'fkimpacto', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'accion', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'analisiscausaraiz', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'fkresponsable', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'estadocro', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'estado'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'id', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'fktipo', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'fkficha', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'origen', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'fkprobabilidad', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'fkimpacto', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'accion', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'analisiscausaraiz', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'fkresponsable', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'estadocro', '' . "\0" . 'App\\Entity\\RiesgosOportunidades' . "\0" . 'estado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (RiesgosOportunidades $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): \App\Entity\RiesgosOportunidades
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkficha(): ?\App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkficha', []);

        return parent::getFkficha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkficha(?\App\Entity\FichaProcesos $fkficha): \App\Entity\RiesgosOportunidades
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkficha', [$fkficha]);

        return parent::setFkficha($fkficha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFktipo(): ?\App\Entity\TipoCRO
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFktipo', []);

        return parent::getFktipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFktipo(?\App\Entity\TipoCRO $fktipo): \App\Entity\RiesgosOportunidades
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFktipo', [$fktipo]);

        return parent::setFktipo($fktipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion(string $descripcion): \App\Entity\RiesgosOportunidades
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigen(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigen', []);

        return parent::getOrigen();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrigen(string $origen): \App\Entity\RiesgosOportunidades
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrigen', [$origen]);

        return parent::setOrigen($origen);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha(\DateTimeInterface $fecha): \App\Entity\RiesgosOportunidades
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkresponsable(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkresponsable', []);

        return parent::getFkresponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkresponsable(?\App\Entity\Usuario $fkresponsable): \App\Entity\RiesgosOportunidades
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkresponsable', [$fkresponsable]);

        return parent::setFkresponsable($fkresponsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(int $estado): \App\Entity\RiesgosOportunidades
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkprobabilidad(): ?\App\Entity\Probabilidad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkprobabilidad', []);

        return parent::getFkprobabilidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkprobabilidad(?\App\Entity\Probabilidad $fkprobabilidad): \App\Entity\RiesgosOportunidades
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkprobabilidad', [$fkprobabilidad]);

        return parent::setFkprobabilidad($fkprobabilidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkimpacto(): ?\App\Entity\Impacto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkimpacto', []);

        return parent::getFkimpacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkimpacto(?\App\Entity\Impacto $fkimpacto): \App\Entity\RiesgosOportunidades
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkimpacto', [$fkimpacto]);

        return parent::setFkimpacto($fkimpacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccion', []);

        return parent::getAccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccion(string $accion): \App\Entity\RiesgosOportunidades
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccion', [$accion]);

        return parent::setAccion($accion);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnalisiscausaraiz(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnalisiscausaraiz', []);

        return parent::getAnalisiscausaraiz();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnalisiscausaraiz(string $analisiscausaraiz): \App\Entity\RiesgosOportunidades
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnalisiscausaraiz', [$analisiscausaraiz]);

        return parent::setAnalisiscausaraiz($analisiscausaraiz);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadocro(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadocro', []);

        return parent::getEstadocro();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadocro(string $estadocro): \App\Entity\RiesgosOportunidades
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadocro', [$estadocro]);

        return parent::setEstadocro($estadocro);
    }

}
