<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Documento extends \App\Entity\Documento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'codigo', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'fkficha', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'fktipo', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'versionvigente', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'fkaprobador', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'vinculoarchivodig', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'vinculodiagflujo', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'fechaPublicacion', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'carpetaOperativa', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'estado'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'codigo', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'fkficha', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'fktipo', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'versionvigente', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'fkaprobador', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'vinculoarchivodig', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'vinculodiagflujo', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'fechaPublicacion', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'carpetaOperativa', '' . "\0" . 'App\\Entity\\Documento' . "\0" . 'estado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Documento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(string $id): \App\Entity\Documento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo(string $codigo): \App\Entity\Documento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkficha(): ?\App\Entity\FichaProcesos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkficha', []);

        return parent::getFkficha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkficha(?\App\Entity\FichaProcesos $fkficha): \App\Entity\Documento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkficha', [$fkficha]);

        return parent::setFkficha($fkficha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFktipo(): ?\App\Entity\TipoDocumento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFktipo', []);

        return parent::getFktipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFktipo(?\App\Entity\TipoDocumento $fktipo): \App\Entity\Documento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFktipo', [$fktipo]);

        return parent::setFktipo($fktipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo(string $titulo): \App\Entity\Documento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersionvigente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersionvigente', []);

        return parent::getVersionvigente();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersionvigente(string $versionvigente): \App\Entity\Documento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersionvigente', [$versionvigente]);

        return parent::setVersionvigente($versionvigente);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkaprobador(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkaprobador', []);

        return parent::getFkaprobador();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkaprobador(?\App\Entity\Usuario $fkaprobador): \App\Entity\Documento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkaprobador', [$fkaprobador]);

        return parent::setFkaprobador($fkaprobador);
    }

    /**
     * {@inheritDoc}
     */
    public function getVinculoarchivodig(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVinculoarchivodig', []);

        return parent::getVinculoarchivodig();
    }

    /**
     * {@inheritDoc}
     */
    public function setVinculoarchivodig(string $vinculoarchivodig): \App\Entity\Documento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVinculoarchivodig', [$vinculoarchivodig]);

        return parent::setVinculoarchivodig($vinculoarchivodig);
    }

    /**
     * {@inheritDoc}
     */
    public function getVinculodiagflujo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVinculodiagflujo', []);

        return parent::getVinculodiagflujo();
    }

    /**
     * {@inheritDoc}
     */
    public function setVinculodiagflujo(string $vinculodiagflujo): \App\Entity\Documento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVinculodiagflujo', [$vinculodiagflujo]);

        return parent::setVinculodiagflujo($vinculodiagflujo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(int $estado): \App\Entity\Documento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarpetaOperativa(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarpetaOperativa', []);

        return parent::getCarpetaOperativa();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarpetaOperativa(string $carpetaOperativa): \App\Entity\Documento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarpetaOperativa', [$carpetaOperativa]);

        return parent::setCarpetaOperativa($carpetaOperativa);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaPublicacion(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaPublicacion', []);

        return parent::getFechaPublicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaPublicacion(\DateTimeInterface $fechaPublicacion): \App\Entity\Documento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaPublicacion', [$fechaPublicacion]);

        return parent::setFechaPublicacion($fechaPublicacion);
    }

}
