<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Auditor extends \App\Entity\Auditor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'item', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'nombres', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'paterno', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'materno', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'apellidosnombres', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'auditorsig', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'profesion', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'vigente', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'estado'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'item', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'nombres', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'paterno', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'materno', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'apellidosnombres', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'auditorsig', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'profesion', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'vigente', '' . "\0" . 'App\\Entity\\Auditor' . "\0" . 'estado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Auditor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): \App\Entity\Auditor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getItem(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItem', []);

        return parent::getItem();
    }

    /**
     * {@inheritDoc}
     */
    public function setItem(int $item): \App\Entity\Auditor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItem', [$item]);

        return parent::setItem($item);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombres(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombres', []);

        return parent::getNombres();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombres(string $nombres): \App\Entity\Auditor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombres', [$nombres]);

        return parent::setNombres($nombres);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaterno(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaterno', []);

        return parent::getPaterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaterno(string $paterno): \App\Entity\Auditor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaterno', [$paterno]);

        return parent::setPaterno($paterno);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaterno(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaterno', []);

        return parent::getMaterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaterno(string $materno): \App\Entity\Auditor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaterno', [$materno]);

        return parent::setMaterno($materno);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidosnombres(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidosnombres', []);

        return parent::getApellidosnombres();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidosnombres(string $apellidosnombres): \App\Entity\Auditor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidosnombres', [$apellidosnombres]);

        return parent::setApellidosnombres($apellidosnombres);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuditorsig(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuditorsig', []);

        return parent::getAuditorsig();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuditorsig(string $auditorsig): \App\Entity\Auditor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuditorsig', [$auditorsig]);

        return parent::setAuditorsig($auditorsig);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesion', []);

        return parent::getProfesion();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesion(string $profesion): \App\Entity\Auditor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesion', [$profesion]);

        return parent::setProfesion($profesion);
    }

    /**
     * {@inheritDoc}
     */
    public function getVigente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVigente', []);

        return parent::getVigente();
    }

    /**
     * {@inheritDoc}
     */
    public function setVigente(string $vigente): \App\Entity\Auditor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVigente', [$vigente]);

        return parent::setVigente($vigente);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(int $estado): \App\Entity\Auditor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

}
