<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Hallazgo extends \App\Entity\Hallazgo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'fkauditoria', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'fktipo', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'ordinal', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'evidencia', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'documento', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'puntoiso', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'fkimpacto', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'fkprobabilidad', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'analisiscausaraiz', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'recomendaciones', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'cargoauditado', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'nombreauditado', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'responsable', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'fecharegistro', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'estado'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'fkauditoria', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'fktipo', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'ordinal', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'evidencia', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'documento', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'puntoiso', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'fkimpacto', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'fkprobabilidad', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'analisiscausaraiz', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'recomendaciones', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'cargoauditado', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'nombreauditado', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'responsable', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'fecharegistro', '' . "\0" . 'App\\Entity\\Hallazgo' . "\0" . 'estado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Hallazgo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(string $id): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkauditoria(): ?\App\Entity\Auditoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkauditoria', []);

        return parent::getFkauditoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkauditoria(?\App\Entity\Auditoria $fkauditoria): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkauditoria', [$fkauditoria]);

        return parent::setFkauditoria($fkauditoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getFktipo(): ?\App\Entity\TipoHallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFktipo', []);

        return parent::getFktipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFktipo(?\App\Entity\TipoHallazgo $fktipo): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFktipo', [$fktipo]);

        return parent::setFktipo($fktipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdinal(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdinal', []);

        return parent::getOrdinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrdinal(int $ordinal): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrdinal', [$ordinal]);

        return parent::setOrdinal($ordinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo(string $titulo): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion(string $descripcion): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvidencia(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvidencia', []);

        return parent::getEvidencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvidencia(string $evidencia): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvidencia', [$evidencia]);

        return parent::setEvidencia($evidencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumento(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumento', []);

        return parent::getDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumento(string $documento): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumento', [$documento]);

        return parent::setDocumento($documento);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuntoiso(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuntoiso', []);

        return parent::getPuntoiso();
    }

    /**
     * {@inheritDoc}
     */
    public function setPuntoiso(string $puntoiso): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuntoiso', [$puntoiso]);

        return parent::setPuntoiso($puntoiso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkimpacto(): ?\App\Entity\Impacto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkimpacto', []);

        return parent::getFkimpacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkimpacto(?\App\Entity\Impacto $fkimpacto): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkimpacto', [$fkimpacto]);

        return parent::setFkimpacto($fkimpacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkprobabilidad(): ?\App\Entity\Probabilidad
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkprobabilidad', []);

        return parent::getFkprobabilidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkprobabilidad(?\App\Entity\Probabilidad $fkprobabilidad): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkprobabilidad', [$fkprobabilidad]);

        return parent::setFkprobabilidad($fkprobabilidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnalisiscausaraiz(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnalisiscausaraiz', []);

        return parent::getAnalisiscausaraiz();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnalisiscausaraiz(string $analisiscausaraiz): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnalisiscausaraiz', [$analisiscausaraiz]);

        return parent::setAnalisiscausaraiz($analisiscausaraiz);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecomendaciones(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecomendaciones', []);

        return parent::getRecomendaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecomendaciones(string $recomendaciones): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecomendaciones', [$recomendaciones]);

        return parent::setRecomendaciones($recomendaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargoauditado(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargoauditado', []);

        return parent::getCargoauditado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargoauditado(string $cargoauditado): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargoauditado', [$cargoauditado]);

        return parent::setCargoauditado($cargoauditado);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreauditado(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreauditado', []);

        return parent::getNombreauditado();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreauditado(string $nombreauditado): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreauditado', [$nombreauditado]);

        return parent::setNombreauditado($nombreauditado);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsable(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsable', []);

        return parent::getResponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsable(string $responsable): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsable', [$responsable]);

        return parent::setResponsable($responsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecharegistro(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecharegistro', []);

        return parent::getFecharegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecharegistro(\DateTimeInterface $fecharegistro): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecharegistro', [$fecharegistro]);

        return parent::setFecharegistro($fecharegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(int $estado): \App\Entity\Hallazgo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

}
