<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AccionController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionEficaciaController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionEficaciaController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionReprogramaController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionReprogramaController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionSeguimientoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionSeguimientoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AreaController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AreaController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AuditorController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AuditorController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AuditoriaController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AuditoriaController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AuditoriaEquipoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AuditoriaEquipoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\CatalogoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\CatalogoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\CategoriaNoticiaController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\CategoriaNoticiaController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ControlCorrelativoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ControlCorrelativoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DatoEmpresarialController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DatoEmpresarialController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocProcRevisionController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocProcRevisionController::aprorec' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocProcRevisionController::derivar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocProcRevisionController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocTipoExtraController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocTipoExtraController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocumentoAdicionalController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocumentoAdicionalController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocumentoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocumentosAsoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocumentosAsoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoCorrelativoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoCorrelativoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoDocumentoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoDocumentoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoNovedadController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoNovedadController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoPersonalController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoPersonalController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoPlanController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoPlanController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoRiesgoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoRiesgoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoSeguimientoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoSeguimientoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FichaCargoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FichaCargoController::aprobarfcgerente' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FichaCargoController::aprobarfcjefe' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FichaCargoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FichaProcesosController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FichaProcesosController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FortalezaController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FortalezaController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GaleriaController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GaleriaController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GerenciaAreaSectorController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GerenciaAreaSectorController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GerenciaController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GerenciaController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GrupoRiesgoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GrupoRiesgoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\HallazgoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\HallazgoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ImpactoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ImpactoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\IndicadorProcesoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\IndicadorProcesoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\NormaDocumentoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\NormaDocumentoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PermisoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PermisoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PersonalCargoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PersonalCargoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PersonalController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PersonalController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PlanAccionController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PlanAccionController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ProbabilidadController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ProbabilidadController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ProcesoRelacionadoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ProcesoRelacionadoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RecursoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RecursoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RecursoNecesarioController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RecursoNecesarioController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RegistroMejoraController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RegistroMejoraController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ResponsabilidadSocialController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ResponsabilidadSocialController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RiesgosOportunidadesController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RiesgosOportunidadesController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SectorController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SectorController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoCroController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoCroController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoElaboracionController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoElaboracionController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoIndicadorController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoIndicadorController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoPlanController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoPlanController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoAuditorController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoAuditorController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoAuditoriaController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoAuditoriaController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoCROController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoCROController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoCargoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoCargoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoDatoEmpresarialController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoDatoEmpresarialController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoDocumentoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoDocumentoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoHallazgoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoHallazgoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoNormaController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoNormaController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoNotaController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoNotaController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoNovedadController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoNovedadController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoPermisoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoPermisoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TurnoController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TurnoController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\UnidadController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\UnidadController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\UnidadMedidaController::actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\UnidadMedidaController::insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionEficaciaController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionEficaciaController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionReprogramaController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionReprogramaController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionSeguimientoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AccionSeguimientoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AreaController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AreaController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AuditorController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AuditorController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AuditoriaController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AuditoriaController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AuditoriaEquipoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\AuditoriaEquipoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\CatalogoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\CatalogoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\CategoriaNoticiaController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\CategoriaNoticiaController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ControlCorrelativoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ControlCorrelativoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DatoEmpresarialController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DatoEmpresarialController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocProcRevisionController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocProcRevisionController:aprorec' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocProcRevisionController:derivar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocProcRevisionController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocTipoExtraController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocTipoExtraController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocumentoAdicionalController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocumentoAdicionalController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocumentoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocumentosAsoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\DocumentosAsoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoCorrelativoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoCorrelativoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoDocumentoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoDocumentoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoNovedadController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoNovedadController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoPersonalController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoPersonalController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoPlanController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoPlanController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoRiesgoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoRiesgoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoSeguimientoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\EstadoSeguimientoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FichaCargoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FichaCargoController:aprobarfcgerente' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FichaCargoController:aprobarfcjefe' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FichaCargoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FichaProcesosController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FichaProcesosController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FortalezaController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\FortalezaController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GaleriaController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GaleriaController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GerenciaAreaSectorController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GerenciaAreaSectorController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GerenciaController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GerenciaController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GrupoRiesgoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\GrupoRiesgoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\HallazgoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\HallazgoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ImpactoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ImpactoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\IndicadorProcesoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\IndicadorProcesoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\NormaDocumentoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\NormaDocumentoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PermisoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PermisoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PersonalCargoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PersonalCargoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PersonalController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PersonalController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PlanAccionController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\PlanAccionController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ProbabilidadController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ProbabilidadController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ProcesoRelacionadoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ProcesoRelacionadoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RecursoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RecursoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RecursoNecesarioController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RecursoNecesarioController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RegistroMejoraController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RegistroMejoraController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ResponsabilidadSocialController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\ResponsabilidadSocialController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RiesgosOportunidadesController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\RiesgosOportunidadesController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SectorController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SectorController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoCroController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoCroController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoElaboracionController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoElaboracionController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoIndicadorController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoIndicadorController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoPlanController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\SeguimientoPlanController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoAuditorController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoAuditorController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoAuditoriaController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoAuditoriaController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoCROController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoCROController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoCargoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoCargoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoDatoEmpresarialController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoDatoEmpresarialController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoDocumentoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoDocumentoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoHallazgoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoHallazgoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoNormaController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoNormaController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoNotaController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoNotaController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoNovedadController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoNovedadController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoPermisoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TipoPermisoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TurnoController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\TurnoController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\UnidadController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\UnidadController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\UnidadMedidaController:actualizar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}, 'App\\Controller\\UnidadMedidaController:insertar' => function () {
    return ($this->privates['.service_locator.eUzYpM2'] ?? $this->load('get_ServiceLocator_EUzYpM2Service.php'));
}))), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
