<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3aADozC\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3aADozC/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3aADozC.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3aADozC\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container3aADozC\srcDevDebugProjectContainer(array(
    'container.build_hash' => '3aADozC',
    'container.build_id' => '8e0a4833',
    'container.build_time' => 1570225294,
), __DIR__.\DIRECTORY_SEPARATOR.'Container3aADozC');
