<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDXcNDaH\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDXcNDaH/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDXcNDaH.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDXcNDaH\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDXcNDaH\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'DXcNDaH',
    'container.build_id' => '752e1890',
    'container.build_time' => 1570198079,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDXcNDaH');
