<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAMxr8Uk\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAMxr8Uk/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAMxr8Uk.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAMxr8Uk\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerAMxr8Uk\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'AMxr8Uk',
    'container.build_id' => '7bf1fe78',
    'container.build_time' => 1570061650,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAMxr8Uk');
